### ISSUE TITLE
Can't link the project under MacOS

### ISSUE THREAD

**Issue by julian-poidevin** [inf0-warri0r/q_snake#1]
Hi,

Thanks for your project ! I'm trying to get this running under XCode developement tool.
I added the Glut and OpenGL framework to my project. When I build the project, I have this error message :

```
ld: 13 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to replace `#include` by `#import`, it didn't make any changes. I also try to separate the header files from the source files. Any clue ?

Thanks a lot.

**Comment by Yuhang-Amber** [comment]
Hi, what does " float convert(float input);" function do? There is  no function definition of this function.
